// DZ Agent V4 PRO — data visualization engine.
// Generates a self-contained Chart.js project (HTML + JS + README) from
// structured input — no LLM call needed for the simple deterministic path,
// which keeps the engine fast and free. Returns files in the same shape as
// the code generator so they can be persisted by project-store.js.
//
// Supported chart types: bar, line, pie, doughnut, radar, polarArea, scatter, bubble.

const CHARTJS_CDN = 'https://cdn.jsdelivr.net/npm/chart.js@4.4.6/dist/chart.umd.min.js'
const SUPPORTED = ['bar', 'line', 'pie', 'doughnut', 'radar', 'polarArea', 'scatter', 'bubble']

export function buildChartProject({ title, type, labels, datasets, data, options } = {}) {
  const chartType = SUPPORTED.includes(type) ? type : 'bar'
  const chartTitle = String(title || 'DZ Agent V4 — Chart').slice(0, 120)

  // Accept either { labels, datasets } or a flat { data: [{label,value}, ...] }
  let chartLabels = labels
  let chartDatasets = datasets
  if ((!chartLabels || !chartDatasets) && Array.isArray(data) && data.length) {
    chartLabels = data.map(d => String(d.label ?? d.name ?? ''))
    chartDatasets = [{
      label: chartTitle,
      data: data.map(d => Number(d.value ?? d.y ?? 0)),
    }]
  }
  if (!Array.isArray(chartLabels) || !Array.isArray(chartDatasets) || chartDatasets.length === 0) {
    throw new Error('chart requires { labels, datasets } or { data: [{label,value},...] }')
  }

  const config = {
    type: chartType,
    data: { labels: chartLabels, datasets: chartDatasets.map(addPalette) },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      plugins: {
        title: { display: true, text: chartTitle, color: '#f3f4f6', font: { size: 18, weight: '700' } },
        legend: { labels: { color: '#cbd5e1' } },
      },
      scales: needsScales(chartType) ? {
        x: { ticks: { color: '#94a3b8' }, grid: { color: 'rgba(148,163,184,0.15)' } },
        y: { ticks: { color: '#94a3b8' }, grid: { color: 'rgba(148,163,184,0.15)' } },
      } : undefined,
      ...(options || {}),
    },
  }

  const configJson = JSON.stringify(config, null, 2)

  const files = [
    {
      path: '/project/index.html',
      lang: 'html',
      content: `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>${escapeHtml(chartTitle)}</title>
  <link rel="stylesheet" href="styles/main.css" />
  <script src="${CHARTJS_CDN}"></script>
</head>
<body>
  <main>
    <h1>${escapeHtml(chartTitle)}</h1>
    <div class="chart-wrap"><canvas id="chart"></canvas></div>
  </main>
  <script src="scripts/chart.js"></script>
</body>
</html>
`,
    },
    {
      path: '/project/styles/main.css',
      lang: 'css',
      content: `:root { color-scheme: dark; }
* { box-sizing: border-box; }
body { margin: 0; font-family: system-ui, sans-serif; background: #0b0b0d; color: #f3f4f6; }
main { max-width: 960px; margin: 3rem auto; padding: 0 1.5rem; }
h1 { margin: 0 0 1.5rem; font-size: 1.75rem; font-weight: 700; }
.chart-wrap { background: #14141a; border: 1px solid #1f1f29; border-radius: 12px; padding: 1.25rem; height: 480px; }
`,
    },
    {
      path: '/project/scripts/chart.js',
      lang: 'js',
      content: `const ctx = document.getElementById('chart').getContext('2d')
const config = ${configJson}
new Chart(ctx, config)
`,
    },
    {
      path: '/project/data.json',
      lang: 'json',
      content: JSON.stringify({ title: chartTitle, type: chartType, labels: chartLabels, datasets: chartDatasets }, null, 2) + '\n',
    },
    {
      path: '/project/README.md',
      lang: 'md',
      content: `# ${chartTitle}

Generated by DZ Agent V4 PRO — chart engine (Chart.js ${chartType}).

## Run

1. Open \`index.html\` in any modern browser.
2. Edit \`data.json\` or regenerate via \`POST /api/dz-agent-v4/chart\`.
3. No build step required.
`,
    },
  ]

  const plan = {
    title: chartTitle,
    stack: 'static',
    description: `${chartType} chart`,
    files: files.map(f => ({ path: f.path, lang: f.lang, purpose: 'chart artefact' })),
    entry: '/project/index.html',
    run: 'open /project/index.html',
    language: 'en',
    kind: 'chart',
  }
  return { plan, files }
}

function needsScales(type) {
  return ['bar', 'line', 'scatter', 'bubble'].includes(type)
}

const PALETTE = [
  ['rgba(34,197,94,0.65)',  'rgba(34,197,94,1)'],
  ['rgba(59,130,246,0.65)', 'rgba(59,130,246,1)'],
  ['rgba(236,72,153,0.65)', 'rgba(236,72,153,1)'],
  ['rgba(234,179,8,0.65)',  'rgba(234,179,8,1)'],
  ['rgba(168,85,247,0.65)', 'rgba(168,85,247,1)'],
  ['rgba(20,184,166,0.65)', 'rgba(20,184,166,1)'],
]

function addPalette(ds, i = 0) {
  const [bg, border] = PALETTE[i % PALETTE.length]
  return {
    backgroundColor: bg,
    borderColor: border,
    borderWidth: 1.5,
    ...ds,
  }
}

function escapeHtml(s) {
  return String(s).replace(/[&<>"']/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c]))
}

export const SUPPORTED_CHART_TYPES = SUPPORTED
