/**
 * Design Intelligence — Token Engine
 * Converts extracted design data into:
 * - CSS custom properties
 * - Tailwind theme config
 * - DESIGN.md markdown
 */

export function generateCssVariables(analysis) {
  const lines = [':root {']

  // Colors
  const palette = analysis.colors.slice(0, 12)
  palette.forEach((color, i) => {
    lines.push(`  --color-${i + 1}: ${color};`)
  })

  // Fonts
  if (analysis.fonts[0]) lines.push(`  --font-primary: '${analysis.fonts[0]}', sans-serif;`)
  if (analysis.fonts[1]) lines.push(`  --font-secondary: '${analysis.fonts[1]}', sans-serif;`)

  // Spacing
  const spacing = analysis.spacing.slice(0, 8)
  spacing.forEach((s, i) => {
    lines.push(`  --spacing-${i + 1}: ${s};`)
  })

  // Border radius
  const radii = analysis.borderRadius.slice(0, 4)
  radii.forEach((r, i) => {
    lines.push(`  --radius-${i + 1}: ${r};`)
  })

  // Shadows
  const shadows = analysis.shadows.slice(0, 3)
  shadows.forEach((s, i) => {
    lines.push(`  --shadow-${i + 1}: ${s};`)
  })

  // Passthrough CSS vars from the site
  const vars = Object.entries(analysis.cssVariables || {}).slice(0, 20)
  if (vars.length > 0) {
    lines.push('\n  /* — Extracted from source — */')
    for (const [k, v] of vars) {
      lines.push(`  ${k}: ${v};`)
    }
  }

  lines.push('}')
  return lines.join('\n')
}

export function generateTailwindTokens(analysis) {
  const colors = {}
  analysis.colors.slice(0, 12).forEach((c, i) => {
    colors[`brand-${i + 1}`] = c
  })

  const fontFamily = {}
  if (analysis.fonts[0]) fontFamily.primary = [analysis.fonts[0], 'sans-serif']
  if (analysis.fonts[1]) fontFamily.secondary = [analysis.fonts[1], 'sans-serif']

  const borderRadius = {}
  analysis.borderRadius.slice(0, 4).forEach((r, i) => {
    borderRadius[`brand-${i + 1}`] = r
  })

  const boxShadow = {}
  analysis.shadows.slice(0, 3).forEach((s, i) => {
    boxShadow[`brand-${i + 1}`] = s
  })

  const config = {
    theme: {
      extend: {
        colors,
        fontFamily,
        borderRadius,
        boxShadow,
      },
    },
  }

  return `/** tailwind.config.js — Auto-generated by DZ Design Intelligence */
module.exports = ${JSON.stringify(config, null, 2)}`
}

export function generateDesignMd(analysis) {
  const lines = []

  lines.push(`# DESIGN.md — ${analysis.title || analysis.url}`)
  lines.push(`> Auto-generated by **DZ Design Intelligence** on ${new Date(analysis.analyzedAt).toLocaleDateString('ar-DZ')}`)
  lines.push(`> Source: \`${analysis.url}\``)
  lines.push(`> UI Style: **${analysis.uiStyle}**`)
  lines.push('')

  lines.push('---')
  lines.push('')
  lines.push('## 🎨 Brand Colors')
  lines.push('')
  lines.push('| Index | Value |')
  lines.push('|-------|-------|')
  analysis.colors.slice(0, 12).forEach((c, i) => {
    lines.push(`| ${i + 1} | \`${c}\` |`)
  })
  lines.push('')

  if (analysis.fonts.length > 0) {
    lines.push('## 🔤 Typography')
    lines.push('')
    analysis.fonts.forEach((f, i) => {
      lines.push(`- **Font ${i + 1}**: \`${f}\``)
    })
    lines.push('')
  }

  if (analysis.spacing.length > 0) {
    lines.push('## 📐 Spacing Scale')
    lines.push('')
    lines.push('```')
    lines.push(analysis.spacing.slice(0, 8).join('  |  '))
    lines.push('```')
    lines.push('')
  }

  if (analysis.borderRadius.length > 0) {
    lines.push('## 🔲 Border Radius')
    lines.push('')
    lines.push('```')
    lines.push(analysis.borderRadius.join('  |  '))
    lines.push('```')
    lines.push('')
  }

  if (analysis.shadows.length > 0) {
    lines.push('## 🌑 Shadows')
    lines.push('')
    analysis.shadows.forEach((s, i) => {
      lines.push(`- **Shadow ${i + 1}**: \`${s}\``)
    })
    lines.push('')
  }

  if (analysis.sections.length > 0) {
    lines.push('## 🧩 Detected Sections')
    lines.push('')
    analysis.sections.forEach(s => lines.push(`- \`${s}\``))
    lines.push('')
  }

  const vars = Object.entries(analysis.cssVariables || {})
  if (vars.length > 0) {
    lines.push('## ⚙️ CSS Variables (Source)')
    lines.push('')
    lines.push('```css')
    lines.push(':root {')
    vars.slice(0, 20).forEach(([k, v]) => lines.push(`  ${k}: ${v};`))
    lines.push('}')
    lines.push('```')
    lines.push('')
  }

  lines.push('---')
  lines.push('')
  lines.push('## 🚀 Usage')
  lines.push('')
  lines.push('1. Copy the CSS variables into your `:root` block')
  lines.push('2. Extend your `tailwind.config.js` with the generated tokens')
  lines.push('3. Use the component library below as a starting point')
  lines.push('')
  lines.push('> Generated by [DZ GPT Design Intelligence](https://dz-gpt.vercel.app)')

  return lines.join('\n')
}

export function generateReactComponent(analysis, componentName = 'GeneratedHero') {
  const primaryColor = analysis.colors[0] || '#6366f1'
  const secondaryColor = analysis.colors[1] || '#8b5cf6'
  const font = analysis.fonts[0] || 'Inter'
  const radius = analysis.borderRadius[0] || '12px'

  return `import React from 'react'

/**
 * ${componentName}
 * Auto-generated by DZ Design Intelligence
 * Based on: ${analysis.url}
 * UI Style: ${analysis.uiStyle}
 */
export default function ${componentName}() {
  return (
    <section style={{
      fontFamily: "'${font}', sans-serif",
      background: '${primaryColor}',
      padding: '80px 24px',
      textAlign: 'center',
      minHeight: '100vh',
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
    }}>
      <h1 style={{
        fontSize: 'clamp(2rem, 5vw, 4rem)',
        fontWeight: 800,
        color: '#fff',
        marginBottom: '24px',
        lineHeight: 1.15,
      }}>
        Your Headline Here
      </h1>
      <p style={{
        fontSize: '1.2rem',
        color: 'rgba(255,255,255,0.8)',
        maxWidth: '600px',
        marginBottom: '40px',
      }}>
        Your compelling subtitle that explains the value proposition clearly and concisely.
      </p>
      <a
        href="#"
        style={{
          background: '${secondaryColor}',
          color: '#fff',
          padding: '16px 40px',
          borderRadius: '${radius}',
          fontSize: '1.1rem',
          fontWeight: 700,
          textDecoration: 'none',
          display: 'inline-block',
        }}
      >
        Get Started
      </a>
    </section>
  )
}
`
}
